### ISSUE TITLE
🐛 Biome client: couldn't create connection to server. with Error: spawn EINVAL

### ISSUE THREAD

**Issue by saramorillon** [biomejs/biome-vscode#297]
### VS Code version

1.92.1

### Extension version

2.3.0

### Biome version

1.8.3

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

When opening VSCode, I get a popup saying "Biome client: couldn't create connection to server."
Here is the stack trace :
```
Biome binary found at C:\Users\Sara\AppData\Roaming\npm\biome.cmd
Executing Biome from: C:\Users\Sara\AppData\Roaming\npm\biome.cmd
[Error - 10:48:32 AM] Biome client: couldn't create connection to server.
Error: spawn EINVAL
	at ChildProcess.spawn (node:internal/child_process:421:11)
	at spawn (node:child_process:799:9)
	at getSocket (c:\Users\Sara\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:36509:57)
	at createMessageTransports (c:\Users\Sara\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:36553:22)
	at LanguageClient2.createMessageTransports (c:\Users\Sara\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:17925:18)
	at LanguageClient2.createConnection (c:\Users\Sara\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:15548:39)
	at LanguageClient2.start (c:\Users\Sara\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:15124:41)
	at activate (c:\Users\Sara\.vscode\extensions\biomejs.biome-2.3.0\out\main.js:36294:16)
	at async m.n (c:\Users\Sara\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6409)
	at async m (c:\Users\Sara\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:6372)
	at async m.l (c:\Users\Sara\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:144:5829)
```
Please note that biome is installed globally. Here are my biome-related settings : 
```json
{
  "editor.codeActionsOnSave": {
    "source.addMissingImports": "explicit",
    "source.organizeImports": "explicit",
    "quickfix.biome": "explicit"
  },
  "biome.lspBin": "C:\\Users\\Sara\\AppData\\Roaming\\npm\\biome.cmd",
  "biome.enabled": true,
}
```
Running biome cli works as expected.

### Steps to reproduce

1. Open VSCode
2. See the error

### Expected behavior

I expect that the extension starts and works correctly.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
Result of `biome rage --daemon-logs` :

CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v22.4.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...
```

**Comment by nhedger** [comment]
I believe this has been fixed in the latest nightly. We've taken a different approach that no longer uses sockets. Would you mind trying?

**Comment by saramorillon** [comment]
Hello,
I installed the nightly version using `npm i -g @biomejs/biome@1.8.4-nightly.d079e53.` Now I can't use biome cli anymore, I get the following error : `Error: Cannot find module '@biomejs/cli-win32-x64/biome.exe'`.

Regarding vscode, I still get the same error: 
![image](https://github.com/user-attachments/assets/046e1f8b-f836-4c4a-8c1c-cbba5d6ab03e)

I also tried with the nightly version of the extension, I get the same error:
![image](https://github.com/user-attachments/assets/c4b927f7-dc8f-42f6-a581-4053695de34b)

Finally, I tried with the prerelease version of the extension, I get a slightly different error:
![image](https://github.com/user-attachments/assets/0510b274-cbe8-44e5-b082-f30cb4fc8f4d)

**Comment by nhedger** [comment]
Could you provide a minimal reproduction repo ?

You can create one easily with the following command:

```shell
npm create @biomejs/biome-reproduction
```

**Comment by saramorillon** [comment]
Here is the reproduction repo :
https://github.com/saramorillon/repro-biome-297

I don't know if it will behave in the same way than the globally installed package.

**Comment by nhedger** [comment]
Does it work for you when using biome from the dependencies of your project ?

**Comment by nhedger** [comment]
Is your `biome.lspBin` setting still set to `C:\\Users\\Sara\\AppData\\Roaming\\npm\\biome.cmd`

If so, could you try changing the path to the actual `.exe` file, not the `.cmd`.
